#!/bin/bash

# pr-cannon Test PR Cleanup Script
# Closes all test PRs with appropriate comments

set -e

# Colors
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m' # No Color

# Configuration
REPO="${1:-is0692vs/test-pr-cannon}"
TEST_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PR_FILE="${TEST_DIR}/pr-numbers.txt"

echo -e "${BLUE}🧹 PR Cannon Test PR Cleanup${NC}\n"
echo "Repository: ${REPO}"
echo ""

# Check if gh command is available
if ! command -v gh &> /dev/null; then
  echo -e "${RED}❌ GitHub CLI (gh) is not installed${NC}"
  echo "Install from: https://cli.github.com/"
  exit 1
fi

# Check if we have PR numbers to close
if [ ! -f "$PR_FILE" ]; then
  echo -e "${RED}❌ No pr-numbers.txt file found${NC}"
  echo "Run './tests/run-tests.sh' first to create test PRs"
  exit 1
fi

# Read PR numbers
PR_NUMBERS=$(cat "$PR_FILE")

if [ -z "$PR_NUMBERS" ]; then
  echo -e "${RED}❌ No PR numbers found${NC}"
  exit 1
fi

echo -e "${YELLOW}Found PRs to close: $PR_NUMBERS${NC}\n"

# Close each PR
for PR_NUM in $PR_NUMBERS; do
  echo -e "${YELLOW}Closing PR #${PR_NUM}...${NC}"
  
  # Add comment before closing
  COMMENT_BODY=$(cat <<EOF
✅ **Test PR Closed**

This PR was created as part of the **Issue #7: Folder/Directory Sending Feature** testing.

- **Test Type:** $([ -f "${TEST_DIR}/pr-${PR_NUM}-type.txt" ] && cat "${TEST_DIR}/pr-${PR_NUM}-type.txt" || echo "Automated test")
- **Feature:** Folder/Directory sending capability for pr-cannon
- **Status:** Tested and verified ✓

This is an automated test PR and is now being closed.

---
*Generated by pr-cannon test cleanup script*
EOF
  )
  
  # Close the PR
  if gh pr close "$PR_NUM" --repo "$REPO" --comment "$COMMENT_BODY"; then
    echo -e "${GREEN}✅ PR #${PR_NUM} closed${NC}"
  else
    echo -e "${RED}❌ Failed to close PR #${PR_NUM}${NC}"
  fi
  
  echo ""
done

# Clean up
rm -f "$PR_FILE"
echo -e "${GREEN}✅ Cleanup completed!${NC}"
